# Generated by Django 3.0.3 on 2020-07-30 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('date_joinedtime', models.DateTimeField(default=datetime.datetime.now)),
                ('hour', models.TimeField(default=datetime.datetime.now)),
                ('hourEntradaM', models.TimeField(blank=True, null=True)),
                ('hourSalidaM', models.TimeField(blank=True, null=True)),
                ('hourEntradaV', models.TimeField(blank=True, null=True)),
                ('hourSalidaV', models.TimeField(blank=True, null=True)),
                ('hourExtra', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Biometrico',
                'verbose_name_plural': 'Biometricos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependence', models.CharField(choices=[('administrativa', 'Administrativa'), ('servicio_cliente', 'Servicio al cliente'), ('tecnica', 'Técnica')], default='administrativa', max_length=50)),
                ('birthdate', models.DateField(default=datetime.datetime.now)),
                ('cant_familiar', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='hombre', max_length=20)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SymptomsEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('body_temperature', models.IntegerField(default=0)),
                ('air_death', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('dry_cough', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('intestinal_discomfort', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('headache', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('lost_taste', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('lost_olfato', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0)),
                ('level_infected', models.BooleanField(default=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Employee')),
            ],
            options={
                'verbose_name': 'Sintoma Empleado',
                'verbose_name_plural': 'Sintomas Empleados',
                'ordering': ['-id'],
            },
        ),
    ]
